apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: locust
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
      - name: locust
        image: locustio/locust:2.24.1
        args:
          - "--worker"
          - "--master-host=locust-master"
          - "--master-port=5557"
          - "--locustfile=/mnt/locust/locustfile.py"
        volumeMounts:
          - name: locustfile
            mountPath: /mnt/locust
      volumes:
        - name: locustfile
          configMap:
            name: locustfile
